# Cloudflare Workers configuration for Next.js frontend with OpenNext
name = "saneatsu-web"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Enable Workers logging
[observability]
enabled = true

# Assets configuration for static files
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# OpenNext configuration will be handled by @opennextjs/cloudflare
# Environment variables are injected via .env file during build

# Development environment
[env.development]
name = "saneatsu-web-dev"

# Service binding to backend API
[[env.development.services]]
binding = "BACKEND_API"
service = "saneatsu-backend-dev"

# Preview/staging environment
[env.preview]
name = "saneatsu-web-preview"

# Service binding to backend API
[[env.preview.services]]
binding = "BACKEND_API"
service = "saneatsu-backend-preview"

# Production environment
[env.production]
name = "saneatsu-web"

# Service binding to backend API
[[env.production.services]]
binding = "BACKEND_API"
service = "saneatsu-backend"

# Custom domain configuration for production
[[env.production.routes]]
pattern = "saneatsu.me/*"
zone_name = "saneatsu.me"