version: 2
updates:
  # npm（pnpm）の依存関係を毎日チェック
  # package.json内のライブラリやフレームワークのバージョンを自動更新
  # 例: react, next.js, typescript など
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # 毎日実行
      time: "08:00" # 午前8時（JST）
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 4 # 同時にオープンするPRは最大4つまで
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)" # コミットメッセージのプレフィックス
